name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'please try to help best you can, any unhelpfull posts are welcome <3'' first issue'
        pr-message: 'im new to github, i dont know what pull requests are, please help me with them! any unhelpfull posts are welcome <3'' first pr'
